<?php
return [
    "fromEmail" => 'info@grdjournals.com',
    "paymentEmail" => 'info@grdjournals.com',
    "adminEmail" => $ADMIN_EMAIL_FROM,
    'productName' => $productName,
    'webUrl' => $webUrl,
    'designElementUrl' => $designElementUrl,
    'Thumbheight'=>$Thumbheight,
    'Thumbwidth'=>$Thumbwidth,
    'dbHostname' => $dbHost,
    'dbUsername' => $dbUser,
    'dbPassword' => $dbPass,
    'dbPort' => $dbPort,
    'dbName' => $dbName,
    'defaultMainLayout' => $defaultMainLayout,
    'tempPath' => $tempPath,
    'superAdminName' => $superAdminName,
    'superAdminId' => $superAdminId,
    'defaultPageSize' => $defaultPageSize,
    'tempPageSize' => $tempPageSize,
    'activeStatus' => $activeStatus,
    'inactiveStatus' => $inactiveStatus,
    'gridNameLimit' => $gridNameLimit,
    'DieselPrice' => 60,
    'PetrolPrice' => 77,
    'KerosenePrice' => 30,
    'ElectricityPrice' => 4,
    'baseProjectLimit' => 2,
    'VillaLimit' => 25,
    "leadsPath" => $uploadPath . "leads/",
    "tendersPath" => $uploadPath . "tenders_documents/",
    "tendersURL" => $uploadUrl . "tenders_documents/",
    "usersPath" => $uploadPath . "users/",
    "usersURL" => $uploadUrl . "users/",
    "itemimgPath" => $uploadPath . "item_images/",
    "itemimgurl" => $uploadUrl . "item_images/",
    "imageUrl" => $imageUrl,
    'dateFormat' => $DATE_FORMAT,
    'dateFormatPHP' => $DATE_FORMAT_PHP,
    'dateTimeFormat' => $DATE_TIME_FORMAT,
    'maxFileSize' => $MAX_FILE_SIZE,
    'allowedImages' => $ALLOWED_IMAGES,
    'allowedFiles' => $ALLOWED_FILES,
    'errorEmail' => $ERROR_USER,    
    "COMPANY_NAME" => $COMPANY_NAME,
    "COMPANY_ADDRESS" => $COMPANY_ADDRESS,
    'modulesList' => [1=>"event",2=>"merchant"],
    'pagesizeArray' => [5=>5, 25=>25, 50=>50, 75=>75, 100=>100, 1000=>'All'],
    'smsUser'=>"grdjournals",
    'smsPassword'=>"Million@456",
    'smsMask'=>"GRDJNL",
];
