<?php
return [
    "fromEmail" => 'info@grdjournals.com',
    "paymentEmail" => 'info@grdjournals.com',
    "adminEmail" => $ADMIN_EMAIL_FROM,
    'productName' => $productName,
    'Thumbheight'=>$Thumbheight,
    'Thumbwidth'=>$Thumbwidth,
    'dbHostname' => $dbHost,
    'dbUsername' => $dbUser,
    'dbPassword' => $dbPass,
    'dbPort' => $dbPort,
    'dbName' => $dbName,
    'defaultPageSize' => $defaultPageSize,
    'tempPageSize' => $tempPageSize,
    'activeStatus' => $activeStatus,
    'inactiveStatus' => $inactiveStatus,
    'gridNameLimit' => $gridNameLimit,
    'dateFormat' => $DATE_FORMAT,
    'dateFormatPHP' => $DATE_FORMAT_PHP,
    'dateTimeFormat' => $DATE_TIME_FORMAT,
    'maxFileSize' => $MAX_FILE_SIZE,
    'allowedImages' => $ALLOWED_IMAGES,
    'allowedFiles' => $ALLOWED_FILES,
    'errorEmail' => $ERROR_USER,    
    "COMPANY_NAME" => $COMPANY_NAME,
    "COMPANY_ADDRESS" => $COMPANY_ADDRESS,
    'pagesizeArray' => [5=>5, 25=>25, 50=>50, 75=>75, 100=>100, 1000=>'All'],
];
