<?php
return [
    "fromEmail" => 'info@grdjournals.com',
    "paymentEmail" => 'payment.grdjournals@gmail.com',
    "adminEmail" => $ADMIN_EMAIL_FROM,
    'productName' => $productName,
    'webUrl' => $webUrl,
    'designElementUrl' => $designElementUrl,
    'dbHostname' => $dbHost,
    'dbUsername' => $dbUser,
    'dbPassword' => $dbPass,
    'dbPort' => $dbPort,
    'dbName' => $dbName,
    'defaultMainLayout' => $defaultMainLayout,
    'tempPath' => $tempPath,
    'defaultPageSize' => $defaultPageSize,
    'tempPageSize' => $tempPageSize,
    'gridNameLimit' => $gridNameLimit,
    "usersPath" => $uploadPath . "users/",
    "usersURL" => $uploadUrl . "users/",
    "imageUrl" => $imageUrl,
    'dateFormat' => $DATE_FORMAT,
    'dateFormatPHP' => $DATE_FORMAT_PHP,
    'dateTimeFormat' => $DATE_TIME_FORMAT,
    'maxFileSize' => $MAX_FILE_SIZE,
    'allowedImages' => $ALLOWED_IMAGES,
    'allowedFiles' => $ALLOWED_FILES,
    'errorEmail' => $ERROR_USER,    
    "COMPANY_NAME" => $COMPANY_NAME,
    "COMPANY_ADDRESS" => $COMPANY_ADDRESS,
    'pagesizeArray' => [5=>5, 25=>25, 50=>50, 75=>75, 100=>100, 1000=>'All'],
    'smsUser'=>"grdjournals",
    'smsPassword'=>"Million@456",
    'smsMask'=>"GRDJNL",
    'insta_key'=>$insta_key,
    'insta_token'=>$insta_token,
    'insta_end_point'=>$insta_end_point,
    "reviewerPath" => $reviewerpath . "reviewer_pic/",
];
